name: module_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

dev_dependencies:
  change_app_package_name: ^1.0.0
  flutter_lints: ^1.0.0
  flutter_markdown: ^0.6.8
  flutter_test:
    sdk: flutter
  markdown: ^4.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/menu.json
    - assets/manual/bootstrap3/home.md
    - assets/manual/bootstrap3/get_started.md
    - assets/manual/bootstrap3/grid_basic.md
    - assets/manual/bootstrap3/typography.md
    - assets/manual/bootstrap3/tables.md
    - assets/manual/bootstrap3/image.md
    - assets/manual/bootstrap3/jumbotron.md
    - assets/manual/bootstrap3/wells.md
    - assets/manual/bootstrap3/alerts.md
    - assets/manual/bootstrap3/buttons.md
    - assets/manual/bootstrap3/button_groups.md
    - assets/manual/bootstrap3/glyphicons.md
    - assets/manual/bootstrap3/badges_labels.md
    - assets/manual/bootstrap3/progress_bars.md
    - assets/manual/bootstrap3/pagination.md
    - assets/manual/bootstrap3/pager.md
    - assets/manual/bootstrap3/list_groups.md
    - assets/manual/bootstrap3/panels.md
    - assets/manual/bootstrap3/dropdowns.md
    - assets/manual/bootstrap3/collapse.md
    - assets/manual/bootstrap3/tabs_pills.md
    - assets/manual/bootstrap3/navbar.md
    - assets/manual/bootstrap3/forms.md
    - assets/manual/bootstrap3/inputs.md
    - assets/manual/bootstrap3/inputs2.md
    - assets/manual/bootstrap3/input_sizing.md
    - assets/manual/bootstrap3/media_objects.md
    - assets/manual/bootstrap3/carousel.md
    - assets/manual/bootstrap3/modal.md
    - assets/manual/bootstrap3/tooltip.md
    - assets/manual/bootstrap3/popover.md
    - assets/manual/bootstrap3/scrollspy.md
    - assets/manual/bootstrap3/affix.md
    - assets/manual/bootstrap3/filters.md
    - assets/manual/bootstrap3/grid_system.md
    - assets/manual/bootstrap3/stacked_horizontal.md
    - assets/manual/bootstrap3/grid_small.md
    - assets/manual/bootstrap3/grid_medium.md
    - assets/manual/bootstrap3/grid_large.md
    - assets/manual/bootstrap3/grid_examples.md
    - assets/manual/bootstrap4/alerts.md
    - assets/manual/bootstrap4/badges.md
    - assets/manual/bootstrap4/button_groups.md
    - assets/manual/bootstrap4/buttons.md
    - assets/manual/bootstrap4/cards.md
    - assets/manual/bootstrap4/carousel.md
    - assets/manual/bootstrap4/collapse.md
    - assets/manual/bootstrap4/colors.md
    - assets/manual/bootstrap4/containers.md
    - assets/manual/bootstrap4/custom_forms.md
    - assets/manual/bootstrap4/dropdown.md
    - assets/manual/bootstrap4/extra_small_layout.md
    - assets/manual/bootstrap4/filters.md
    - assets/manual/bootstrap4/flex.md
    - assets/manual/bootstrap4/forms.md
    - assets/manual/bootstrap4/get_started.md
    - assets/manual/bootstrap4/grid_basic.md
    - assets/manual/bootstrap4/grid_extra_large.md
    - assets/manual/bootstrap4/grid_large.md
    - assets/manual/bootstrap4/grid_medium.md
    - assets/manual/bootstrap4/grid_small.md
    - assets/manual/bootstrap4/grid_system.md
    - assets/manual/bootstrap4/grid_xsmall.md
    - assets/manual/bootstrap4/home.md
    - assets/manual/bootstrap4/icons.md
    - assets/manual/bootstrap4/images.md
    - assets/manual/bootstrap4/input_groups.md
    - assets/manual/bootstrap4/inputs.md
    - assets/manual/bootstrap4/jumbotron.md
    - assets/manual/bootstrap4/list_groups.md
    - assets/manual/bootstrap4/media_objects.md
    - assets/manual/bootstrap4/modal.md
    - assets/manual/bootstrap4/navbar.md
    - assets/manual/bootstrap4/navs.md
    - assets/manual/bootstrap4/pagination.md
    - assets/manual/bootstrap4/popover.md
    - assets/manual/bootstrap4/progress_bars.md
    - assets/manual/bootstrap4/scrollspy.md
    - assets/manual/bootstrap4/spinners.md
    - assets/manual/bootstrap4/stacked_horizontal.md
    - assets/manual/bootstrap4/tables.md
    - assets/manual/bootstrap4/toast.md
    - assets/manual/bootstrap4/tooltip.md
    - assets/manual/bootstrap4/typography.md
    - assets/manual/bootstrap4/utilities.md
    - assets/manual/bootstrap5/Alerts.md
    - assets/manual/bootstrap5/Badges.md
    - assets/manual/bootstrap5/Button_Groups.md
    - assets/manual/bootstrap5/Buttons.md
    - assets/manual/bootstrap5/Cards.md
    - assets/manual/bootstrap5/Carousel.md
    - assets/manual/bootstrap5/Checks_and_Radios.md
    - assets/manual/bootstrap5/Collapse.md
    - assets/manual/bootstrap5/Colors.md
    - assets/manual/bootstrap5/Containers.md
    - assets/manual/bootstrap5/Dropdowns.md
    - assets/manual/bootstrap5/Examples.md
    - assets/manual/bootstrap5/Flex.md
    - assets/manual/bootstrap5/Floating_Labels.md
    - assets/manual/bootstrap5/Form_Validation.md
    - assets/manual/bootstrap5/Forms.md
    - assets/manual/bootstrap5/Get_Started.md
    - assets/manual/bootstrap5/Grid_Basic.md
    - assets/manual/bootstrap5/Grid_System.md
    - assets/manual/bootstrap5/home.md
    - assets/manual/bootstrap5/Images.md
    - assets/manual/bootstrap5/Input_Groups.md
    - assets/manual/bootstrap5/Jumbotron.md
    - assets/manual/bootstrap5/Large.md
    - assets/manual/bootstrap5/List_Groups.md
    - assets/manual/bootstrap5/Medium.md
    - assets/manual/bootstrap5/Modal.md
    - assets/manual/bootstrap5/Navbars.md
    - assets/manual/bootstrap5/Navs.md
    - assets/manual/bootstrap5/Offcanvas.md
    - assets/manual/bootstrap5/Pagination.md
    - assets/manual/bootstrap5/Popover.md
    - assets/manual/bootstrap5/Progress_Bars.md
    - assets/manual/bootstrap5/Range.md
    - assets/manual/bootstrap5/Scrollspy.md
    - assets/manual/bootstrap5/Select_Menus.md
    - assets/manual/bootstrap5/Small.md
    - assets/manual/bootstrap5/Spinners.md
    - assets/manual/bootstrap5/Stacked_horizontal.md
    - assets/manual/bootstrap5/Tables.md
    - assets/manual/bootstrap5/Toasts.md
    - assets/manual/bootstrap5/Tooltip.md
    - assets/manual/bootstrap5/Typography.md
    - assets/manual/bootstrap5/Utilities.md
    - assets/manual/bootstrap5/XLarge.md
    - assets/manual/bootstrap5/XSmall.md
    - assets/manual/bootstrap5/XXL.md

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Source Code
      fonts:
        - asset: assets/fonts/SourceCodePro-Regular.ttf
        - asset: assets/fonts/SourceCodePro-Medium.ttf
          weight: 500
        - asset: assets/fonts/SourceCodePro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SourceCodePro-SemiBold.ttf
          weight: 800
        - asset: assets/fonts/SourceCodePro-Black.ttf
          weight: 900
    - family: Source Sans
      fonts:
        - asset: assets/fonts/SourceSansPro-Regular.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
